name: test5-for-user-testing
on:
  push:
    branches:
    - yamlOutPutTesting
jobs:
  Testing-With-DotNet-1:
    name: Testing-With-DotNet-1
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: cd Test && dotnet restore
    - name: Run tests
      run: cd Test && dotnet test --no-build --configuration Release --verbosity normal
